// Generated by Wrangler — extended with Better Auth + D1 bindings
interface CloudflareEnv {
  DB: D1Database;
  KV: KVNamespace;
  ASSETS: Fetcher;
  IMAGES: ImagesBinding;
  WORKER_SELF_REFERENCE: Fetcher;

  // Better Auth env vars
  BETTER_AUTH_URL: string;
  BETTER_AUTH_TRUSTED_ORIGINS: string;
		BETTER_AUTH_SECRET: string;
		ADMIN_EMAIL: string;

  // Supabase (legacy — remove after migration verified)
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;

  // Stripe
  STRIPE_MODE: "test" | "live";
  STRIPE_SECRET_KEY: string;
  STRIPE_PRICE_PREMIUM_MONTHLY: string;
  STRIPE_PRICE_PREMIUM_ANNUAL: string;
  STRIPE_PRICE_FAMILY_MONTHLY: string;
  STRIPE_PRICE_FAMILY_ANNUAL: string;
  STRIPE_PRICE_EXTENDED_QUESTIONS_MONTHLY: string;

  // Email
  SEND_EMAIL: SendEmail;
  STRIPE_WEBHOOK_SECRET: string;
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
  NEXT_PUBLIC_SITE_URL: string;

  // AI and text-to-speech providers
  DEEPSEEK_API_KEY: string;
  ELEVENLABS_API_KEY: string;
  GATHOS_TTS_KEY: string;
}
